### ISSUE TITLE
类似 colors 抽象类无法生成映射

### ISSUE THREAD

**Issue by acsweets** [zmtzawqlp/fair_gallery#1]
![image](https://github.com/zmtzawqlp/fair_gallery/assets/87525862/f764908e-304f-4f75-9f90-1119bb6b2f46)
 
![image](https://github.com/zmtzawqlp/fair_gallery/assets/87525862/14d85488-b51d-4718-93f3-b2f3aec94031)

![image](https://github.com/zmtzawqlp/fair_gallery/assets/87525862/f49cba88-cc25-4cb1-9cfe-77238e263e31)
  有些抽象类需要生成映射有些不需要

**Comment by zmtzawqlp** [comment]
https://github.com/zmtzawqlp/fair/commit/dd3d814ed4f63f3b9d79c2472505296f1490215c

感觉是官方又改了。或者有新语法了。之前还针对这个改过。哎

**Comment by zmtzawqlp** [comment]
你是用我的demo 来执行的吗？fixed 分支

**Comment by acsweets** [comment]
对啊就是你这个demo，3.13.4.那个分支

**Comment by zmtzawqlp** [comment]
提供下 flutter 环境信息

**Comment by zmtzawqlp** [comment]
![image](https://github.com/zmtzawqlp/fair_gallery/assets/16477333/734c2fa5-d928-4646-a097-a01db6c0ef38)

可以生成的。。建议把 fair 的 fixed 分支拉下来，然后 demo 的引用都 override 本地的。。再执行

**Comment by zmtzawqlp** [comment]
# fair:
  #   path: ../Fair/fair  
  # fair_compiler:
  #   path: ../Fair/compiler
  # fair_dart2dsl:
  #   path: ../Fair/dart2dsl
  # fair_dart2js:
  #   path: ../Fair/dart2js        

看起来新的sdk 下面， git 引用的方式不能不用了。。你全部改成本地引用吧

**Comment by acsweets** [comment]
fair 的 fixed 分支 指的是啥啊  fair中没有这个分支啊 , 本地引用的你的分支， 

<img width="567" alt="image" src="https://github.com/zmtzawqlp/fair_gallery/assets/87525862/1be9b7bb-468b-4767-acde-0c3d96e3ba7d">

<img width="771" alt="image" src="https://github.com/zmtzawqlp/fair_gallery/assets/87525862/7f96f502-8e74-4fe2-bdc8-4bba36f0d890">


环境
<img width="590" alt="image" src="https://github.com/zmtzawqlp/fair_gallery/assets/87525862/6c7849d2-dd90-40d6-8b23-f9b98b8ec053">

**Comment by zmtzawqlp** [comment]
https://github.com/zmtzawqlp/fair/tree/fixed.   然后肯定有些地方会报错。自己按照文章中的版本自己调整下，比如 import 改改， replace 改改

**Comment by zmtzawqlp** [comment]
https://github.com/zmtzawqlp/fair

* main 分支基于 3.13 以下
* fixed 分支基于 3.13 以及以上
